spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://140.83.53.129:3306/sys?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
mybatis:
  mapper-locations: mybatis/**/*.xml
server:
  port: 8080