spring:
  datasource:
    url: jdbc:mariadb://140.83.53.129:3306/sys?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
