spring:
  profiles:
    active: local
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB #Default : 10MB
      max-request-size: 5MB #Default : 10MB
server:
  port: 8080